USE [master]
GO

/****** Object:  Database [Eliza]    Script Date: 22/05/2019 18:50:41 ******/
CREATE DATABASE [Eliza]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Eliza', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Eliza.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Eliza_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Eliza_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Eliza] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Eliza].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Eliza] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Eliza] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Eliza] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Eliza] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Eliza] SET ARITHABORT OFF 
GO

ALTER DATABASE [Eliza] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Eliza] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Eliza] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Eliza] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Eliza] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Eliza] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Eliza] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Eliza] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Eliza] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Eliza] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Eliza] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Eliza] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Eliza] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Eliza] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Eliza] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Eliza] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Eliza] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Eliza] SET RECOVERY FULL 
GO

ALTER DATABASE [Eliza] SET  MULTI_USER 
GO

ALTER DATABASE [Eliza] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Eliza] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Eliza] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Eliza] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Eliza] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Eliza] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Eliza] SET  READ_WRITE 
GO

